<?php

namespace app\Table\Profile\ProfileCommunity\ProfileContactsPart;

use app\App;
use app\Table\AppDisplay;
use core\Session\Session;
use app\Table\Profile\Quickinfos\QuickInfosModel;

use app\Table\AppDisplayElem;

class displayProfileContactPart extends AppDisplay
{
    protected $pageName;
    private $nbContacts;
    private $personnaleState; //0 => I'm not a contact of this user, 1 => invitation sent, 2 => i'm a contact of this user
    private $idUserToDisplay;
    private $userCompleteName;

    public function __construct($nbContacts = false, $idUserToDisplay = false, $personnaleState = false)
    {
        $this->pageName = 'profile';
        parent::__construct(false, $this->pageName);
        //ces test sont réalisé car cette classe peux etre appelé avec un paramètre un utilisateur, comme dans inc/MyCommunity/block
        $this->nbContacts =          $nbContacts;
        $this->personnaleState =     $personnaleState;

        if($idUserToDisplay)
        {
            $this->idUserToDisplay =    $idUserToDisplay;
            $model =                    new QuickInfosModel();
            $this->userCompleteName =   $model->getCompleteNameFromUserid($this->idUserToDisplay);
        }
    }

    public function showBtImContact()
    {
        return '<button class="bt-remove-contact" id="remove-contact" data-toremove="'. $this->idUserToDisplay .'">
                    -
                </button>';
    }

    public function showBtImNotContact()
    {
        return '<button class="share-button bt" id="add-contact" data-toadd="'. $this->idUserToDisplay .'">
                    +
                </button>';
    }

    public function showBtImPendingContact()
    {
        return '<button class="bt-pending-contact" id="pending-contact" data-cancelask="'. $this->idUserToDisplay .'">
                    -
                </button>';
    }

    public function showImContactPart()
    {
        return '<div class="col-md-6 contacts">
                    <h3 class="col-md-12">'. $this->langFile[$this->pageName]->title_gamer_contactsection .'</h3>
                    <p class="counter-contacts">'. $this->nbContacts .'</p>
                    <div class="bt-add-container">
                        '. $this->showBtImContact() .'                       
                    </div>
                </div>';
    }

    public function showImPendingPart()
    {
        return '<div class="col-md-6 contacts">
                    <h3 class="col-md-12">'. $this->langFile[$this->pageName]->title_gamer_contactsection .'</h3>
                    <p class="counter-contacts">'. $this->nbContacts .'</p>
                    <div class="bt-add-container">
                        '. $this->showBtImPendingContact() .'                       
                    </div>
                </div>';
    }

    public function showImNotContactPart()
    {
        return '<div class="col-md-6 contacts">
                    <h3 class="col-md-12">'. $this->langFile[$this->pageName]->title_gamer_contactsection .'</h3>
                    <p class="counter-contacts">'. $this->nbContacts .'</p>
                    <div class="bt-add-container">
                        '. $this->showBtImNotContact() .'                       
                    </div>
                </div>';
    }

    public function show()
    {
        if(Session::getInstance()->read('current-state')['state'] == 'owner')
        {
           // nothing to do,owner part is just a number generated by the function getMynbFollowers in core\AppProfile
        }
        if(Session::getInstance()->read('current-state')['state'] == 'viewer')
        {
            if($this->personnaleState == 0)
            {
                return $this->showImNotContactPart();
            }
            if($this->personnaleState == 1)
            {
                return $this->showImPendingPart();
            }
            if($this->personnaleState == 2)
            {
                return $this->showImContactPart();
            }
        }
    }
}