<?php

namespace app\Table\Profile\ProfileCommunity\ProfileFollowerPart;

use app\App;
use app\Table\AppDisplay;
use core\Session\Session;
use app\Table\Profile\Quickinfos\QuickInfosModel;

use app\Table\AppDisplayElem;

class displayProfileFollowerPart extends AppDisplay
{
    protected $pageName;
    private $nbFollowers;
    private $personnaleState; //0 => I'm not a follower of this guy, 1 => i'm following
    private $idUserToDisplay;
    private $userCompleteName;

    public function __construct($nbFollowers = false, $idUserToDisplay = false, $personnaleState = false)
    {
        $this->pageName = 'profile';
        parent::__construct(false, $this->pageName);
        //ces test sont réalisé car cette classe peux etre appelé avec un paramètre un utilisateur, comme dans inc/MyCommunity/block
        $this->nbFollowers =          $nbFollowers;
        $this->personnaleState =      $personnaleState;

        if($idUserToDisplay)
        {
            $this->idUserToDisplay =  $idUserToDisplay;
            $model =                new QuickInfosModel();
            $this->userCompleteName = $model->getCompleteNameFromUserid($this->idUserToDisplay);
        }
    }

    public function showBtImFollowing()
    {
        return '<button class="bt-unfollow" id="add-follower" data-tounfollow="'. $this->idUserToDisplay .'">
                    -
                </button>';
    }

    public function showBtImNotFollowing()
    {
        return '<button class="share-button bt" id="add-follower" data-tofollow="'. $this->idUserToDisplay .'">
                    +
                </button>';
    }

    public function showImFollowingPart()
    {
        return '<div class="col-md-6 folowers">
                    <h3 class="col-md-12">'. $this->langFile[$this->pageName]->title_gamer_followersection .'</h3>
                    <p class="counter-folower">'. $this->nbFollowers .'</p>
                    <div class="bt-add-container">
                        '. $this->showBtImFollowing() .'                       
                    </div>
                </div>';
    }

    public function showImNotFollowingPart()
    {
        return '<div class="col-md-6 folowers">
                    <h3 class="col-md-12">'. $this->langFile[$this->pageName]->title_gamer_followersection .'</h3>
                    <p class="counter-folower">'. $this->nbFollowers .'</p>
                    <div class="bt-add-container">
                        '. $this->showBtImNotFollowing() .'                       
                    </div>
                </div>';
    }

    public function show()
    {
        if(Session::getInstance()->read('current-state')['state'] == 'owner')
        {
           // nothing to do,owner part is just a number generated by the function getMynbFollowers in core\AppProfile
        }
        if(Session::getInstance()->read('current-state')['state'] == 'viewer')
        {
            if(!$this->personnaleState)
            {
                return $this->showImNotFollowingPart();
            }
            if($this->personnaleState == 1)
            {
                return $this->showImFollowingPart();
            }
        }
    }
}